### ISSUE TITLE
[OCIS] Add parameter to disable Kopano user survey

### ISSUE THREAD

**Issue by michaelstingl** [owncloud-docker/compose-playground#13]
> By default, any running konnectd regularly transmits survey data to a Kopano user survey service at https://stats.kopano.io . To disable participation, set the environment variable `KOPANO_SURVEYCLIENT_AUTOSURVEY` to `no`.

From: https://github.com/Kopano-dev/konnect#usage-survey

@micbar @IljaN What do you think?

**Comment by IljaN** [comment]
Survey is not part of ocis-konnectd. Close?
