### ISSUE TITLE
Cannot change log level

### ISSUE THREAD

**Issue by davitol** [owncloud-docker/compose-playground#39]
Trying to change the log level using `owncloud/base:latest` image running the following commands in the CLI :

```
www-data@2646743682c7: ~/owncloud # occ log:manage --level debug
Enabled logging backend: owncloud
Log level: Debug (0)
Log timezone: UTC

www-data@2646743682c7: ~/owncloud # occ log:manage
Enabled logging backend: owncloud
Log level: Warning (2)
Log timezone: UTC
```

**Comment by xoxys** [comment]
In a docker env, it's always recommended starting the container with the desired configuration via environment variables. Nevertheless, this can only be fixed upstream, see https://github.com/owncloud-docker/base/pull/149/files
