### ISSUE TITLE
example oc10-with-ocis-infra fails to start

### ISSUE THREAD

**Issue by jnweiger** [owncloud-docker/compose-playground#50]
The documented setup in the README of
https://github.com/owncloud-docker/compose-playground/tree/master/examples/oc10-with-ocis-infra#oidc-login

Does not work for me. port 9200 is open, but all connections are immediately closed.

```
$ telnet ocis 9200
Trying 127.0.0.1...
Connected to ocis.
Escape character is '^]'.
Connection closed by foreign host.
```

**Comment by jnweiger** [comment]
As discussed today, this should be an alternative to https://github.com/owncloud-docker/compose-playground/issues/6

It isn't. Please escalate appropriately to unblock one of the two.

**Comment by Cyb3rDudu** [comment]
oc10-with-ocis-infra is obsolete. The server setup is in the official docs of the ocis repository.
This example will be deleted.
